### Products
GET http://localhost:3000/products

### Products By ID
GET http://localhost:3000/products/2

### Crear nuevo Product
POST http://localhost:3000/products
Content-Type: application/json

{
    "sql": "SELECT * FROM products",
    "name": "Logic Watch",
    "description": "Intelligent Watch",
    "price": 5,
    "stock": 10,
    "category": "Technology"
}

### Update some product data
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
    "price": 550
}


### Delete some product data
DELETE http://localhost:3000/products/19

// ------------------------------------------
// ------------------------------------------
// ----------- Users Authentication
// ------------------------------------------
// ------------------------------------------
###
POST http://localhost:3000/register
Content-Type: application/json

{
   "username": "ronaldo",
    "password": "123456"
} 

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "username": "ronaldo",
    "password": "123456"
}

